version: '3.2'
services:
  main:
    image: tsmean/latex2html:2
    deploy:
      # placement:
      #   constraints:
      #     - node.labels.w1 == true
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      labels:
        - "traefik.frontend.rule=Host:latex2html.tsmean.com"
        - "traefik.port=46536"
        - "traefik.docker.network=traefik"
    ports:
      - "46536:46536"
    networks:
      - traefik

networks:
  traefik:
    external: true
